server:
  port: 10086
  tomcat:
    max-http-header-size: 8192

spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

    #取消自己注册到eureka
    register-with-eureka: false
    fetch-registry: false
