server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:

    gateway:
      routes:
        - id: user-server-route
          uri: lb://SERVICE-PRIVIDER-USER
          predicates:
            - Path=/**
          filters:
            #添加前缀
            - PrefixPath=/user
#            - #去除前缀
           #- StripPrefix=1

      #过滤器
      default-filters:
         - AddResponseHeader=i-like,heima

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

